name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: pruebas+coverage
        id: pruebas
        run: | 
          export FLASK_APP=src/app.py PYTHONPATH=./ FLASK_ENV=testing TESTING=True FLASK_DEBUG=False FLASK_APP_NAME=md-apisecurity
          python -m coverage run -m unittest discover -v -s src/tests/ -p 'test_*.py' 
          python -m coverage xml -i 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
